# Reviewed macOS package and application setup.

tap "grafana/grafana"
tap "makisuo/tap", "https://github.com/Makisuo/homebrew-tap"

brew "awscli"
brew "cloc"
brew "cmake"
brew "fzf"
brew "gh"
brew "go"
brew "helm"
brew "helmfile"
brew "herdr"
brew "k3d"
brew "k9s"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "mole"
brew "neovim"
brew "railway"
brew "uv"
brew "grafana/grafana/gcx", trusted: true
brew "makisuo/tap/maple", trusted: true

cask "cap"
cask "codex"
cask "docker-desktop"
cask "gcloud-cli"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "lens"
cask "ngrok"
cask "notion"
cask "openusage"
cask "raycast"
cask "tg-pro"
cask "yaak"

vscode "astro-build.astro-vscode"
vscode "bierner.comment-tagged-templates"
vscode "bierner.folder-source-actions"
vscode "boto3typed.boto3-ide"
vscode "bradlc.vscode-tailwindcss"
vscode "chekweitan.compare-view"
vscode "csstools.postcss"
vscode "dbaeumer.vscode-eslint"
vscode "digitalbrainstem.javascript-ejs-support"
vscode "docker.docker"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "effectful-tech.effect-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "iulian-radu-at.find-unused-exports"
vscode "kamikillerto.vscode-colorize"
vscode "mechatroner.rainbow-csv"
vscode "meganrogge.template-string-converter"
vscode "mermaidchart.vscode-mermaid-chart"
vscode "miguelsolorio.fluent-icons"
vscode "miguelsolorio.symbols"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "origin-space.shadcn-color-tool"
vscode "orta.vscode-twoslash-queries"
vscode "oven.bun-vscode"
vscode "oxc.oxc-vscode"
vscode "quick-lint.quick-lint-js"
vscode "sleistner.vscode-fileutils"
vscode "typescriptteam.native-preview"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
vscode "yoavbls.pretty-ts-errors"

go "golang.org/x/tools/gopls"

# Requested and recommended baseline additions.
brew "bat"
brew "eza"
brew "fd"
brew "gitleaks"
brew "git"
brew "jq"
brew "python"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stow"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "font-jetbrains-mono-nerd-font"
cask "slack"
cask "visual-studio-code"
cask "zed"
